name: Release to itch.io

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./GAME_OFF

    steps:
    - uses: actions/checkout@v2
      with:
        repository: pandepic/ElementEngine
        path: ./ElementEngine    
    - uses: actions/checkout@v2
      with:
        repository: pandepic/GAME_OFF_2020
        path: ./GAME_OFF
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build Windows
      run: dotnet publish -r win-x64 -c Release --output build-windows
    - name: Build Osx
      run: dotnet publish -r osx-x64 -c ReleaseOGL --output build-osx
    - name: Build Linux
      run: dotnet publish -r linux-x64 -c ReleaseOGL --output build-linux
    - name: Clean NetCoreBeauty
      run: find . -name 'NetCoreBeauty' -type f -delete
    - name: Publish Windows build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: captain-shostakovich
        ITCH_USER: pandepic
        PACKAGE: ./GAME_OFF/build-windows
    - name: Publish OSX build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: osx
        ITCH_GAME: captain-shostakovich
        ITCH_USER: pandepic
        PACKAGE: ./GAME_OFF/build-osx
    - name: Publish Linux build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: captain-shostakovich
        ITCH_USER: pandepic
        PACKAGE: ./GAME_OFF/build-linux
